// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: handheld_gui_v1_1

#include "../ui.h"

void ui_memScreen_screen_init(void)
{
    ui_memScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_memScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_memScreen, lv_color_hex(0xB4E2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_memScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_memScreen, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_memScreen);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(96));
    lv_obj_set_height(ui_Container4, lv_pct(20));
    lv_obj_set_x(ui_Container4, lv_pct(0));
    lv_obj_set_y(ui_Container4, lv_pct(-24));
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_Container4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xF5F1F4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chipType = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_chipType, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_chipType, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_chipType, lv_pct(3));
    lv_obj_set_y(ui_chipType, lv_pct(19));
    lv_label_set_text(ui_chipType, "Chip type");
    lv_obj_set_style_text_font(ui_chipType, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chipTypeLabel = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_chipTypeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_chipTypeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_chipTypeLabel, lv_pct(21));
    lv_obj_set_y(ui_chipTypeLabel, lv_pct(20));
    lv_label_set_text(ui_chipTypeLabel, "XXXXXXXXXXX");
    lv_obj_set_style_text_font(ui_chipTypeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_epcSize = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_epcSize, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_epcSize, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_epcSize, lv_pct(3));
    lv_obj_set_y(ui_epcSize, lv_pct(53));
    lv_label_set_text(ui_epcSize, "EPC size ");
    lv_obj_set_style_text_font(ui_epcSize, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_epcSizeLabel = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_epcSizeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_epcSizeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_epcSizeLabel, lv_pct(21));
    lv_obj_set_y(ui_epcSizeLabel, lv_pct(53));
    lv_label_set_text(ui_epcSizeLabel, "XX");
    lv_obj_set_style_text_font(ui_epcSizeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totalMem = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_totalMem, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_totalMem, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_totalMem, lv_pct(50));
    lv_obj_set_y(ui_totalMem, lv_pct(19));
    lv_label_set_text(ui_totalMem, "Total memory");
    lv_obj_set_style_text_font(ui_totalMem, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_totatMemoryLabel = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_totatMemoryLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_totatMemoryLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_totatMemoryLabel, lv_pct(77));
    lv_obj_set_y(ui_totatMemoryLabel, lv_pct(20));
    lv_label_set_text(ui_totatMemoryLabel, "XX");
    lv_obj_set_style_text_font(ui_totatMemoryLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tidSize = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_tidSize, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tidSize, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tidSize, lv_pct(27));
    lv_obj_set_y(ui_tidSize, lv_pct(53));
    lv_label_set_text(ui_tidSize, "TID size");
    lv_obj_set_style_text_font(ui_tidSize, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tidSizeLabel = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_tidSizeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_tidSizeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_tidSizeLabel, lv_pct(43));
    lv_obj_set_y(ui_tidSizeLabel, lv_pct(53));
    lv_label_set_text(ui_tidSizeLabel, "XX");
    lv_obj_set_style_text_font(ui_tidSizeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwdSize = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_pwdSize, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_pwdSize, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_pwdSize, lv_pct(75));
    lv_obj_set_y(ui_pwdSize, lv_pct(52));
    lv_label_set_text(ui_pwdSize, "PWD size");
    lv_obj_set_style_text_font(ui_pwdSize, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userSize = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_userSize, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_userSize, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_userSize, lv_pct(50));
    lv_obj_set_y(ui_userSize, lv_pct(53));
    lv_label_set_text(ui_userSize, "User size");
    lv_obj_set_style_text_font(ui_userSize, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_userSizeLabel = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_userSizeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_userSizeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_userSizeLabel, lv_pct(68));
    lv_obj_set_y(ui_userSizeLabel, lv_pct(53));
    lv_label_set_text(ui_userSizeLabel, "XX");
    lv_obj_set_style_text_font(ui_userSizeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pwdSizeLabel = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_pwdSizeLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_pwdSizeLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_pwdSizeLabel, lv_pct(94));
    lv_obj_set_y(ui_pwdSizeLabel, lv_pct(50));
    lv_label_set_text(ui_pwdSizeLabel, "XX");
    lv_obj_set_style_text_font(ui_pwdSizeLabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // ui_TestBtn = ui_normalBtn_create(ui_memScreen);
    // lv_obj_set_x(ui_TestBtn, lv_pct(-40));
    // lv_obj_set_y(ui_TestBtn, lv_pct(-42));

    // lv_label_set_text(ui_comp_get_child(ui_TestBtn, UI_COMP_NORMALBTN_NORMALBTNLABEL), "Test");

    // ui_TestBtn1 = ui_normalBtn_create(ui_memScreen);
    // lv_obj_set_x(ui_TestBtn1, lv_pct(-23));
    // lv_obj_set_y(ui_TestBtn1, lv_pct(-42));

    // ui_TestBtn2 = ui_normalBtn_create(ui_memScreen);
    // lv_obj_set_x(ui_TestBtn2, lv_pct(-6));
    // lv_obj_set_y(ui_TestBtn2, lv_pct(-42));

    // lv_label_set_text(ui_comp_get_child(ui_TestBtn2, UI_COMP_NORMALBTN_NORMALBTNLABEL), "Auth");

    uint16_t btn_radius = 8;
    ui_home2 = lv_btn_create(ui_memScreen);
    lv_obj_set_width(ui_home2, 25);
    lv_obj_set_height(ui_home2, 25);
    lv_obj_align(ui_home2, LV_ALIGN_BOTTOM_LEFT, 3, -3);
    lv_obj_add_flag(ui_home2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_home2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_home2, btn_radius, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t *ui_home_btn_label = lv_label_create(ui_home2);
    lv_obj_set_align(ui_home_btn_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_home_btn_label, LV_SYMBOL_HOME);

    lv_obj_add_event_cb(ui_home2, ui_home_btn_cb, LV_EVENT_CLICKED, NULL); /*Home button callback*/
    /*table*/
    table1 = lv_table_create(ui_memScreen);
    // col
    lv_table_set_col_cnt(table1, 9);
    lv_table_set_col_width(table1, 0, 35.55);
    lv_table_set_col_width(table1, 1, 35.55);
    lv_table_set_col_width(table1, 2, 35.55);
    lv_table_set_col_width(table1, 3, 35.55);
    lv_table_set_col_width(table1, 4, 35.55);
    lv_table_set_col_width(table1, 5, 35.55);
    lv_table_set_col_width(table1, 6, 35.55);
    lv_table_set_col_width(table1, 7, 35.55);
    lv_table_set_col_width(table1, 8, 35.55);
    // row
    lv_table_set_row_cnt(table1, 2);
    // lv_obj_set_height(table1, 60);
    lv_table_set_cell_value(table1, 0, 0, "MEM.");
    lv_table_set_cell_value(table1, 1, 0, "EPC");
    lv_table_set_cell_value(table1, 2, 0, "TID");
    // lv_table_set_cell_value(table1, 3, 0, "USR.");
    lv_table_set_cell_value(table1, 0, 1, "word0");
    lv_table_set_cell_value(table1, 0, 2, "word1");
    lv_table_set_cell_value(table1, 0, 3, "word2");
    lv_table_set_cell_value(table1, 0, 4, "word3");
    lv_table_set_cell_value(table1, 0, 5, "word4");
    lv_table_set_cell_value(table1, 0, 6, "word5");
    lv_table_set_cell_value(table1, 0, 7, "word6");
    lv_table_set_cell_value(table1, 0, 8, "word7");
    lv_obj_align(table1, LV_ALIGN_TOP_MID, 0, 0);
    lv_obj_set_pos(table1, 0, lv_pct(38));
    lv_obj_set_scroll_dir(table1, LV_DIR_VER);
    lv_obj_set_style_pad_ver(table1, 3, LV_PART_ITEMS);
    lv_obj_set_style_pad_hor(table1, 0, LV_PART_ITEMS);
    lv_obj_set_style_bg_color(table1, lv_color_hex(0xfffbe6), LV_PART_ITEMS);
    // flags
    lv_obj_add_flag(table1, LV_OBJ_FLAG_SCROLL_ONE | LV_OBJ_FLAG_PRESS_LOCK);
    lv_obj_clear_flag(table1, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);

    /*table scrolllbar styles*/
    // static lv_style_t table_scrollbar_style;
    // lv_style_init(&table_scrollbar_style);
    // lv_style_set_bg_color(&table_scrollbar_style, lv_color_hex(0xFF2400));
    // lv_style_set_width(&table_scrollbar_style, 14);
    // lv_style_set_pad_right(&table_scrollbar_style, 10);
    // lv_obj_add_style(table, &table_scrollbar_style, LV_PART_SCROLLBAR);
    /*table properties*/
    /*mem scr keyboard*/

    /*NOTIFY LABEL*/
    ui_memScreenNotifyLabel = lv_label_create(ui_memScreen);
    lv_obj_set_width(ui_memScreenNotifyLabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_memScreenNotifyLabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_y(ui_memScreenNotifyLabel, -5);
    lv_obj_set_x(ui_memScreenNotifyLabel, lv_pct(-2));
    lv_obj_set_align(ui_memScreenNotifyLabel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_memScreenNotifyLabel, "");
    lv_obj_clear_flag(ui_memScreenNotifyLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                          LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                          LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    // lv_obj_add_flag(ui_memScreenNotifyLabel, LV_OBJ_FLAG_HIDDEN); /// Flags
    /*DATA INPUT PANEL*/
    ui_memScrPanel = lv_obj_create(ui_memScreen);
    lv_obj_set_width(ui_memScrPanel, lv_pct(50));
    lv_obj_set_height(ui_memScrPanel, lv_pct(33));
    lv_obj_set_x(ui_memScrPanel, -3);
    lv_obj_set_y(ui_memScrPanel, -56);
    lv_obj_set_align(ui_memScrPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_memScrPanel, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_memScrPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_shadow_color(ui_memScrPanel, lv_color_hex(0x655151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_memScrPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_memScrPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_memScrPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_memScrPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_memScrPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_memscrNotifypanelClose = lv_btn_create(ui_memScrPanel);
    lv_obj_set_width(ui_memscrNotifypanelClose, lv_pct(30));
    lv_obj_set_height(ui_memscrNotifypanelClose, lv_pct(40));
    lv_obj_set_x(ui_memscrNotifypanelClose, lv_pct(-43));
    lv_obj_set_y(ui_memscrNotifypanelClose, lv_pct(-53));
    lv_obj_set_align(ui_memscrNotifypanelClose, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_memscrNotifypanelClose, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_memscrNotifypanelClose, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_memscrNotifypanelClose, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notifyPanelclosebuttonlabel2 = lv_label_create(ui_memscrNotifypanelClose);
    lv_obj_set_width(ui_notifyPanelclosebuttonlabel2, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_notifyPanelclosebuttonlabel2, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_notifyPanelclosebuttonlabel2, lv_pct(-5));
    lv_obj_set_y(ui_notifyPanelclosebuttonlabel2, lv_pct(0));
    lv_obj_set_align(ui_notifyPanelclosebuttonlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notifyPanelclosebuttonlabel2, "close");
    lv_obj_set_style_text_font(ui_notifyPanelclosebuttonlabel2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_memScrNotifyPanellabel = lv_label_create(ui_memScrPanel);
    lv_obj_set_width(ui_memScrNotifyPanellabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_memScrNotifyPanellabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_memScrNotifyPanellabel, -43);
    lv_obj_set_y(ui_memScrNotifyPanellabel, -7);
    lv_obj_set_align(ui_memScrNotifyPanellabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_memScrNotifyPanellabel, "Enter data :");

    ui_memScrTextarea = lv_textarea_create(ui_memScrPanel);
    lv_obj_set_width(ui_memScrTextarea, 80);
    lv_obj_set_height(ui_memScrTextarea, 29);
    lv_obj_set_x(ui_memScrTextarea, 30);
    lv_obj_set_y(ui_memScrTextarea, -6);
    lv_obj_set_align(ui_memScrTextarea, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_memScrTextarea, "abcdefABCDEF0123456789");
    lv_obj_clear_flag(ui_memScrTextarea,
                      LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                          LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags

    ui_memScrWriteData = lv_btn_create(ui_memScrPanel);
    lv_obj_set_width(ui_memScrWriteData, lv_pct(30));
    lv_obj_set_height(ui_memScrWriteData, lv_pct(40));
    lv_obj_set_x(ui_memScrWriteData, lv_pct(38));
    lv_obj_set_y(ui_memScrWriteData, lv_pct(47));
    lv_obj_set_align(ui_memScrWriteData, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_memScrWriteData, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_memScrWriteData, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_memScrWriteData, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notifyPanelclosebuttonlabel1 = lv_label_create(ui_memScrWriteData);
    lv_obj_set_width(ui_notifyPanelclosebuttonlabel1, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_notifyPanelclosebuttonlabel1, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_notifyPanelclosebuttonlabel1, lv_pct(-5));
    lv_obj_set_y(ui_notifyPanelclosebuttonlabel1, lv_pct(0));
    lv_obj_set_align(ui_notifyPanelclosebuttonlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notifyPanelclosebuttonlabel1, "Write");
    lv_obj_set_style_text_font(ui_notifyPanelclosebuttonlabel1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    /*PANEL END*/
    /*AUTH PANEL*/
    ui_authPanel = lv_obj_create(ui_memScreen);
    lv_obj_set_width(ui_authPanel, lv_pct(65));
    lv_obj_set_height(ui_authPanel, lv_pct(43));
    lv_obj_set_x(ui_authPanel, -1);
    lv_obj_set_y(ui_authPanel, -61);
    lv_obj_set_align(ui_authPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_authPanel, LV_OBJ_FLAG_HIDDEN);       /// Flags
    lv_obj_clear_flag(ui_authPanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_radius(ui_authPanel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_authPanel, lv_color_hex(0x655151), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_authPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_authPanel, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_authPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_authPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_authPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainScrNotifypanelClose3 = lv_btn_create(ui_authPanel);
    lv_obj_set_width(ui_mainScrNotifypanelClose3, 44);
    lv_obj_set_height(ui_mainScrNotifypanelClose3, 22);
    lv_obj_set_x(ui_mainScrNotifypanelClose3, lv_pct(-44));
    lv_obj_set_y(ui_mainScrNotifypanelClose3, lv_pct(46));
    lv_obj_set_align(ui_mainScrNotifypanelClose3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mainScrNotifypanelClose3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_mainScrNotifypanelClose3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_mainScrNotifypanelClose3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_notifyPanelclosebuttonlabel7 = lv_label_create(ui_mainScrNotifypanelClose3);
    lv_obj_set_width(ui_notifyPanelclosebuttonlabel7, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_notifyPanelclosebuttonlabel7, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_notifyPanelclosebuttonlabel7, lv_pct(-5));
    lv_obj_set_y(ui_notifyPanelclosebuttonlabel7, lv_pct(0));
    lv_obj_set_align(ui_notifyPanelclosebuttonlabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_notifyPanelclosebuttonlabel7, "Close");
    lv_obj_set_style_text_font(ui_notifyPanelclosebuttonlabel7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passASCIIlabel = lv_label_create(ui_authPanel);
    lv_obj_set_width(ui_passASCIIlabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_passASCIIlabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_passASCIIlabel, -55);
    lv_obj_set_y(ui_passASCIIlabel, -26);
    lv_obj_set_align(ui_passASCIIlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_passASCIIlabel, "Pass. ASCII");
    lv_obj_set_style_text_font(ui_passASCIIlabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passASCIItxtarea = lv_textarea_create(ui_authPanel);
    lv_obj_set_width(ui_passASCIItxtarea, 100);
    lv_obj_set_height(ui_passASCIItxtarea, 28);
    lv_obj_set_x(ui_passASCIItxtarea, lv_pct(17));
    lv_obj_set_y(ui_passASCIItxtarea, lv_pct(-40));
    lv_obj_set_align(ui_passASCIItxtarea, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_passASCIItxtarea, " ABCDEFGHIJKLMNOPQRSTUVWXYZ_-.@#");
    lv_obj_clear_flag(ui_passASCIItxtarea,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                          LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_text_font(ui_passASCIItxtarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_passASCIItxtarea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_max_length(ui_passASCIItxtarea, 6);
    ui_passHEXtxtarea = lv_textarea_create(ui_authPanel);
    lv_obj_set_width(ui_passHEXtxtarea, 100);
    lv_obj_set_height(ui_passHEXtxtarea, 28);
    lv_obj_set_x(ui_passHEXtxtarea, lv_pct(17));
    lv_obj_set_y(ui_passHEXtxtarea, lv_pct(4));
    lv_obj_set_align(ui_passHEXtxtarea, LV_ALIGN_CENTER);
    lv_textarea_set_accepted_chars(ui_passHEXtxtarea, "abcdefABCDEF0123456789");
    lv_obj_clear_flag(ui_passHEXtxtarea,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE |
                          LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_style_text_font(ui_passHEXtxtarea, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_passHEXtxtarea, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_textarea_set_max_length(ui_passHEXtxtarea, 8);
    ui_passHEXlabel = lv_label_create(ui_authPanel);
    lv_obj_set_width(ui_passHEXlabel, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_passHEXlabel, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_passHEXlabel, -57);
    lv_obj_set_y(ui_passHEXlabel, 1);
    lv_obj_set_align(ui_passHEXlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_passHEXlabel, "Pass. HEX");
    lv_obj_set_style_text_font(ui_passHEXlabel, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    // lv_obj_add_event_cb(ui_memscrNotifypanelClose, ui_event_memscrNotifypanelClose, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_memScrTextarea, ui_event_memScrTextarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_memScrWriteData, ui_event_memScrWriteData, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_memScrWriteData, mem_scr_write, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_mainScrNotifypanelClose3, ui_event_memScrNotifypanelClose3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passASCIItxtarea, ui_event_passASCIItxtarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passASCIItxtarea, ui_event_passASCIItxtareaVC, LV_EVENT_ALL, "asciiTextarea");
    lv_obj_add_event_cb(ui_passHEXtxtarea, ui_event_passHEXtxtarea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_passHEXtxtarea, ui_event_passHEXtxtareaVC, LV_EVENT_ALL, "hexTextarea");
    lv_obj_add_event_cb(table1, table1_click_event, LV_EVENT_LONG_PRESSED, NULL);
}
