// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: tabs

#include "../ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel3, lv_pct(65));
    lv_obj_set_height(ui_Panel3, lv_pct(49));
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 5);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button5 = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_Button5, 20);
    lv_obj_set_height(ui_Button5, 20);
    lv_obj_set_x(ui_Button5, 0);
    lv_obj_set_y(ui_Button5, -2);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea3 = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_TextArea3, 80);
    lv_obj_set_height(ui_TextArea3, 28);
    lv_obj_set_x(ui_TextArea3, -42);
    lv_obj_set_y(ui_TextArea3, 2);
    lv_obj_set_align(ui_TextArea3, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea3, "Placeholder...");



    ui_TextArea4 = lv_textarea_create(ui_Panel3);
    lv_obj_set_width(ui_TextArea4, 80);
    lv_obj_set_height(ui_TextArea4, 28);
    lv_obj_set_x(ui_TextArea4, 47);
    lv_obj_set_y(ui_TextArea4, 2);
    lv_obj_set_align(ui_TextArea4, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea4, "Placeholder...");



    ui_tap_write = lv_btn_create(ui_Panel3);
    lv_obj_set_width(ui_tap_write, 40);
    lv_obj_set_height(ui_tap_write, 20);
    lv_obj_set_x(ui_tap_write, 0);
    lv_obj_set_y(ui_tap_write, 2);
    lv_obj_set_align(ui_tap_write, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_tap_write, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_tap_write, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_tap_write);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Write");

    ui_Label6 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -41);
    lv_obj_set_y(ui_Label6, -24);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "ASCII");

    ui_Label1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 45);
    lv_obj_set_y(ui_Label1, -24);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "HEX");

}
