// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: tabs

#include "../ui.h"

void ui_setupScreen_screen_init(void)
{
    ui_setupScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_setupScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_tabview = lv_tabview_create(ui_setupScreen, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_tabview, lv_pct(100));
    lv_obj_set_height(ui_tabview, lv_pct(100));
    lv_obj_set_align(ui_tabview, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tabview, LV_OBJ_FLAG_SCROLLABLE); /// Flags

    ui_tab1 = lv_tabview_add_tab(ui_tabview, "Wifi");

    ui_wifi_setup = lv_label_create(ui_tab1);
    lv_obj_set_width(ui_wifi_setup, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifi_setup, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifi_setup, -112);
    lv_obj_set_y(ui_wifi_setup, -82);
    lv_obj_set_align(ui_wifi_setup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifi_setup, "WiFi Setup");

    ui_wifi_ssid_dd = lv_dropdown_create(ui_tab1);
    lv_dropdown_set_options(ui_wifi_ssid_dd, "SSID");
    lv_obj_set_width(ui_wifi_ssid_dd, 150);
    lv_obj_set_height(ui_wifi_ssid_dd, 40);
    lv_obj_set_x(ui_wifi_ssid_dd, -76);
    lv_obj_set_y(ui_wifi_ssid_dd, -48);
    lv_obj_set_align(ui_wifi_ssid_dd, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_ssid_dd, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_set_style_radius(ui_wifi_ssid_dd, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifi_ssid_dd, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifi_ssid_dd, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifi_ssid_dd, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wifi_ssid_dd, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(lv_dropdown_get_list(ui_wifi_ssid_dd), 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_wifi_ssid_dd), lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_wifi_ssid_dd), 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(lv_dropdown_get_list(ui_wifi_ssid_dd), 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(lv_dropdown_get_list(ui_wifi_ssid_dd), LV_BORDER_SIDE_LEFT,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_pass_ta = lv_textarea_create(ui_tab1);
    lv_obj_set_width(ui_wifi_pass_ta, 150);
    lv_obj_set_height(ui_wifi_pass_ta, 40);
    lv_obj_set_x(ui_wifi_pass_ta, -76);
    lv_obj_set_y(ui_wifi_pass_ta, 0);
    lv_obj_set_align(ui_wifi_pass_ta, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifi_pass_ta, "Password");
    lv_obj_clear_flag(ui_wifi_pass_ta, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                                           LV_OBJ_FLAG_SCROLL_CHAIN); /// Flags
    lv_obj_set_scrollbar_mode(ui_wifi_pass_ta, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_radius(ui_wifi_pass_ta, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifi_pass_ta, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifi_pass_ta, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifi_pass_ta, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wifi_pass_ta, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_av_network_container = lv_obj_create(ui_tab1);
    lv_obj_remove_style_all(ui_av_network_container);
    lv_obj_set_width(ui_av_network_container, 136);
    lv_obj_set_height(ui_av_network_container, 152);
    lv_obj_set_x(ui_av_network_container, 79);
    lv_obj_set_y(ui_av_network_container, 10);
    lv_obj_set_align(ui_av_network_container, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_av_network_container, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_av_network_container, lv_color_hex(0xDFDEDE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_av_network_container, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_available_network_label = lv_label_create(ui_tab1);
    lv_obj_set_width(ui_available_network_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_available_network_label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_available_network_label, 78);
    lv_obj_set_y(ui_available_network_label, -82);
    lv_obj_set_align(ui_available_network_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_available_network_label, "Available Networks");

    ui_wifi_scan_btn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_wifi_scan_btn, 45);
    lv_obj_set_height(ui_wifi_scan_btn, 25);
    lv_obj_set_x(ui_wifi_scan_btn, -107);
    lv_obj_set_y(ui_wifi_scan_btn, 44);
    lv_obj_set_align(ui_wifi_scan_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_scan_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_wifi_scan_btn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_wifi_scan_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifi_scan_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi_scan_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifi_scan_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifi_scan_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifi_scan_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wifi_scan_btn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifi_scan_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifi_scan_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_scan_btn_label = lv_label_create(ui_wifi_scan_btn);
    lv_obj_set_width(ui_wifi_scan_btn_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifi_scan_btn_label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_wifi_scan_btn_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifi_scan_btn_label, "Scan");
    lv_obj_set_style_text_color(ui_wifi_scan_btn_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifi_scan_btn_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_conn_btn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_wifi_conn_btn, 45);
    lv_obj_set_height(ui_wifi_conn_btn, 25);
    lv_obj_set_x(ui_wifi_conn_btn, -41);
    lv_obj_set_y(ui_wifi_conn_btn, 44);
    lv_obj_set_align(ui_wifi_conn_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_conn_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_wifi_conn_btn, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_radius(ui_wifi_conn_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifi_conn_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi_conn_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifi_conn_btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wifi_conn_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifi_conn_btn, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_wifi_conn_btn, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifi_conn_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifi_conn_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_conn_btn_label = lv_label_create(ui_wifi_conn_btn);
    lv_obj_set_width(ui_wifi_conn_btn_label, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifi_conn_btn_label, LV_SIZE_CONTENT); /// 1
    lv_obj_set_align(ui_wifi_conn_btn_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifi_conn_btn_label, "Conn");
    lv_obj_set_style_text_color(ui_wifi_conn_btn_label, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifi_conn_btn_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi_save_checkbox = lv_checkbox_create(ui_tab1);
    lv_checkbox_set_text(ui_wifi_save_checkbox, "Save Network");
    lv_obj_set_width(ui_wifi_save_checkbox, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_wifi_save_checkbox, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_wifi_save_checkbox, -65);
    lv_obj_set_y(ui_wifi_save_checkbox, 75);
    lv_obj_set_align(ui_wifi_save_checkbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifi_save_checkbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags

    ui_offset = lv_label_create(ui_tab1);
    lv_obj_set_width(ui_offset, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_offset, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_offset, 3);
    lv_obj_set_y(ui_offset, 153);
    lv_obj_set_align(ui_offset, LV_ALIGN_CENTER);
    lv_obj_add_flag(wn_panel, LV_OBJ_FLAG_HIDDEN);

    ui_tab2 = lv_tabview_add_tab(ui_tabview, "RFID");

    ui_tab3 = lv_tabview_add_tab(ui_tabview, "Setup");

    /* events */
    lv_obj_add_event_cb(wnp_close_btn, wnp_close_btn_cb, LV_EVENT_CLICKED, NULL);
}
void wnp_create(const char *msg)
{
    lv_obj_clear_flag(wn_panel, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(wnp_msg, msg);
}
void wnp_del(const char *msg)
{
    lv_obj_add_flag(wn_panel, LV_OBJ_FLAG_HIDDEN);
    lv_label_set_text(wnp_msg, "");
}
