// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: tabs

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel2, lv_pct(55));
    lv_obj_set_height(ui_Panel2, lv_pct(40));
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 10);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button4, 20);
    lv_obj_set_height(ui_Button4, 20);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -29);
    lv_obj_set_y(ui_Label5, -7);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Data");

    ui_TextArea2 = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextArea2, 80);
    lv_obj_set_height(ui_TextArea2, 30);
    lv_obj_set_x(ui_TextArea2, 32);
    lv_obj_set_y(ui_TextArea2, -8);
    lv_obj_set_align(ui_TextArea2, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea2, "Data");
    lv_obj_clear_flag(ui_TextArea2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags



    ui_Button2 = lv_btn_create(ui_Panel2);
    lv_obj_set_width(ui_Button2, 40);
    lv_obj_set_height(ui_Button2, 20);
    lv_obj_set_align(ui_Button2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
