// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: tabs

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x958C8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui_tag_auth_panel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_ui_tag_auth_panel, 171);
    lv_obj_set_height(ui_ui_tag_auth_panel, 108);
    lv_obj_set_x(ui_ui_tag_auth_panel, 0);
    lv_obj_set_y(ui_ui_tag_auth_panel, 8);
    lv_obj_set_align(ui_ui_tag_auth_panel, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_ui_tag_auth_panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ui_tag_auth_panel, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui_tag_auth_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ui_tag_auth_panel, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ui_tag_auth_panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_ui_tag_auth_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ui_tag_auth_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ui_tag_auth_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ui_tag_auth_panel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui_tap_pass_ascii_label = lv_label_create(ui_ui_tag_auth_panel);
    lv_obj_set_width(ui_ui_tap_pass_ascii_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ui_tap_pass_ascii_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ui_tap_pass_ascii_label, -46);
    lv_obj_set_y(ui_ui_tap_pass_ascii_label, -26);
    lv_obj_set_align(ui_ui_tap_pass_ascii_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui_tap_pass_ascii_label, "ASCII");

    ui_ui_tap_pass_ascii_ta = lv_textarea_create(ui_ui_tag_auth_panel);
    lv_obj_set_width(ui_ui_tap_pass_ascii_ta, 80);
    lv_obj_set_height(ui_ui_tap_pass_ascii_ta, 32);
    lv_obj_set_x(ui_ui_tap_pass_ascii_ta, 24);
    lv_obj_set_y(ui_ui_tap_pass_ascii_ta, -28);
    lv_obj_set_align(ui_ui_tap_pass_ascii_ta, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ui_tap_pass_ascii_ta, "pass...");
    lv_obj_clear_flag(ui_ui_tap_pass_ascii_ta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ui_tap_pass_ascii_ta, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui_tap_pass_ascii_ta, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ui_tap_pass_hex_label = lv_label_create(ui_ui_tag_auth_panel);
    lv_obj_set_width(ui_ui_tap_pass_hex_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ui_tap_pass_hex_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ui_tap_pass_hex_label, -46);
    lv_obj_set_y(ui_ui_tap_pass_hex_label, 10);
    lv_obj_set_align(ui_ui_tap_pass_hex_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui_tap_pass_hex_label, "HEX");

    ui_ui_tap_pass_hex_ta = lv_textarea_create(ui_ui_tag_auth_panel);
    lv_obj_set_width(ui_ui_tap_pass_hex_ta, 80);
    lv_obj_set_height(ui_ui_tap_pass_hex_ta, 32);
    lv_obj_set_x(ui_ui_tap_pass_hex_ta, 24);
    lv_obj_set_y(ui_ui_tap_pass_hex_ta, 9);
    lv_obj_set_align(ui_ui_tap_pass_hex_ta, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_ui_tap_pass_hex_ta, "pass...");
    lv_obj_clear_flag(ui_ui_tap_pass_hex_ta, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ui_tap_pass_hex_ta, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui_tap_pass_hex_ta, 0, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_ui_tap_write = lv_btn_create(ui_ui_tag_auth_panel);
    lv_obj_set_height(ui_ui_tap_write, 21);
    lv_obj_set_width(ui_ui_tap_write, lv_pct(50));
    lv_obj_set_align(ui_ui_tap_write, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ui_tap_write, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ui_tap_write, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ui_tap_write, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui_tap_write, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui_tap_write, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ui_tap_write, lv_color_hex(0xDADADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ui_tap_write, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui_tap_write, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ui_tap_write, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_ui_tap_write);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Write");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x57A0F0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui_tap_close = lv_btn_create(ui_ui_tag_auth_panel);
    lv_obj_set_height(ui_ui_tap_close, 21);
    lv_obj_set_width(ui_ui_tap_close, lv_pct(50));
    lv_obj_set_align(ui_ui_tap_close, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ui_tap_close, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ui_tap_close, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ui_tap_close, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ui_tap_close, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ui_tap_close, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ui_tap_close, lv_color_hex(0xDADADE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ui_tap_close, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ui_tap_close, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_ui_tap_close, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ui_tap_close_label = lv_label_create(ui_ui_tap_close);
    lv_obj_set_width(ui_ui_tap_close_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ui_tap_close_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ui_tap_close_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ui_tap_close_label, "Close");
    lv_obj_set_style_text_color(ui_ui_tap_close_label, lv_color_hex(0xFE3723), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ui_tap_close_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}
