// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: tabs

#ifndef _TABS_UI_H
#define _TABS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_setupScreen
void ui_setupScreen_screen_init(void);
extern lv_obj_t * ui_setupScreen;
extern lv_obj_t * ui_tabview;
extern lv_obj_t * ui_tab1;
extern lv_obj_t * ui_wifi_setup;
extern lv_obj_t * ui_wifi_ssid_dd;
extern lv_obj_t * ui_wifi_pass_ta;
extern lv_obj_t * ui_av_network_container;
extern lv_obj_t * ui_available_network_label;
extern lv_obj_t * ui_wifi_scan_btn;
extern lv_obj_t * ui_wifi_scan_btn_label;
extern lv_obj_t * ui_wifi_conn_btn;
extern lv_obj_t * ui_wifi_conn_btn_label;
extern lv_obj_t * ui_wifi_save_checkbox;
extern lv_obj_t * ui_offset;
extern lv_obj_t * ui_tab2;
extern lv_obj_t * ui_tab3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
